const inventory = [
  {
    category: 'Spirits',
    name: 'Absolut Vodka',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 13.99,
    sellingPrice: 15.99,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: 'Absolut Vanilla',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 13.99,
    sellingPrice: 15.99,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: 'Absolut Raspberri',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 13.99,
    sellingPrice: 15.99,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: 'Aperol',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 8,
    sellingPrice: 12,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: 'Barenjager',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 28,
    sellingPrice: 30.34,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: 'Beefeater',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 13.99,
    sellingPrice: 15.99,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: 'Beefeater Pink',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 13.99,
    sellingPrice: 15.99,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: 'Beefeater Blood Orange',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 13.99,
    sellingPrice: 15.99,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: 'Bombay Sapphire',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 19,
    sellingPrice: 21.5,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: 'Havana 3',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 15.99,
    sellingPrice: 18.99,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: 'Havana 7',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 19.99,
    sellingPrice: 23.25,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: 'Jagermeister',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 8,
    sellingPrice: 12,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: 'Jamesons',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 17,
    sellingPrice: 21.23,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: 'Olmeca Blanco',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 14,
    sellingPrice: 16.99,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: 'Olmeca Reposado',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 14,
    sellingPrice: 16.99,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: ' Tanqueray',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 9,
    sellingPrice: 13,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
  {
    category: 'Spirits',
    name: ' Tanqueray No. Ten Gin',
    status: 'In Stock',
    dateNotified: null,
    costPrice: 22,
    sellingPrice: 25,
    supplierName: 'LWC',
    supplierDetails: {
      address: 'Unit 3 Stainburn Rd, Openshaw, Manchester M11 2DN',
      phone: '0161 438 4088',
    },
  },
];

export default inventory;
